[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules']
test = 'test'
solc = '0.5.16'
optimizer = true
optimizer_runs = 999999
evm_version = 'istanbul'
remappings = ['openzeppelin-solidity-2.3.0/=node_modules/openzeppelin-solidity-2.3.0/']

[rpc_endpoints]
kub_testnet = "${KUB_TESTNET_RPC}"
kub_mainnet = "${KUB_MAINNET_RPC}"
